A = int(input())
B = int(input())
C = int(input())

result = A * B * C
result = list(str(result))
result = list(map(int, result))
count0 = result.count(0)
count1 = result.count(1)
count2 = result.count(2)
count3 = result.count(3)
count4 = result.count(4)
count5 = result.count(5)
count6 = result.count(6)
count7 = result.count(7)
count8 = result.count(8)
count9 = result.count(9)

print(count0)
print(count1)
print(count2)
print(count3)
print(count4)
print(count5)
print(count6)
print(count7)
print(count8)
print(count9)